/**
 * js/foods.js — Food calorie database for Nutrify
 * 300+ items across all major world cuisines.
 * Each entry: { name, calories, unit }
 * calories = kcal per unit (e.g. per 1 serving, per 100g, per piece)
 */
const FOODS = [
  // ── Indian — North Indian ─────────────────────────────
  { name: 'Butter Chicken (1 serving)', calories: 490 },
  { name: 'Dal Makhani (1 bowl)', calories: 320 },
  { name: 'Paneer Butter Masala (1 serving)', calories: 410 },
  { name: 'Roti / Chapati (1 piece)', calories: 80 },
  { name: 'Paratha (1 piece)', calories: 200 },
  { name: 'Aloo Paratha (1 piece)', calories: 260 },
  { name: 'Naan (1 piece)', calories: 260 },
  { name: 'Rajma Chawal (1 plate)', calories: 450 },
  { name: 'Chole Bhature (1 plate)', calories: 580 },
  { name: 'Palak Paneer (1 serving)', calories: 280 },
  { name: 'Aloo Gobi (1 serving)', calories: 180 },
  { name: 'Matar Paneer (1 serving)', calories: 300 },
  { name: 'Dal Tadka (1 bowl)', calories: 220 },
  { name: 'Jeera Rice (1 bowl)', calories: 280 },
  { name: 'Biryani — Chicken (1 plate)', calories: 520 },
  { name: 'Biryani — Veg (1 plate)', calories: 380 },
  { name: 'Biryani — Mutton (1 plate)', calories: 580 },
  { name: 'Samosa (1 piece)', calories: 130 },
  { name: 'Pakora (6 pieces)', calories: 200 },
  { name: 'Pav Bhaji (1 plate)', calories: 420 },
  { name: 'Poha (1 bowl)', calories: 250 },
  { name: 'Upma (1 bowl)', calories: 230 },
  { name: 'Khichdi (1 bowl)', calories: 300 },
  { name: 'Kadhi Chawal (1 plate)', calories: 380 },
  { name: 'Methi Thepla (1 piece)', calories: 120 },
  { name: 'Dhokla (4 pieces)', calories: 180 },
  { name: 'Kachori (1 piece)', calories: 180 },
  { name: 'Lassi — Sweet (1 glass)', calories: 220 },
  { name: 'Lassi — Salted (1 glass)', calories: 120 },
  { name: 'Mango Lassi (1 glass)', calories: 260 },
  { name: 'Paneer Tikka (6 pieces)', calories: 300 },
  { name: 'Tandoori Chicken (2 pieces)', calories: 320 },
  { name: 'Chicken Tikka (6 pieces)', calories: 280 },
  { name: 'Seekh Kebab (2 pieces)', calories: 240 },
  { name: 'Shahi Paneer (1 serving)', calories: 380 },
  { name: 'Malai Kofta (1 serving)', calories: 420 },
  { name: 'Halwa — Sooji (1 bowl)', calories: 350 },
  { name: 'Gulab Jamun (2 pieces)', calories: 280 },
  { name: 'Jalebi (4 pieces)', calories: 300 },
  { name: 'Kheer (1 bowl)', calories: 260 },
  // ── Indian — South Indian ─────────────────────────────
  { name: 'Idli (2 pieces)', calories: 130 },
  { name: 'Dosa — Plain (1 piece)', calories: 170 },
  { name: 'Masala Dosa (1 piece)', calories: 300 },
  { name: 'Uttapam (1 piece)', calories: 200 },
  { name: 'Sambar (1 bowl)', calories: 100 },
  { name: 'Coconut Chutney (2 tbsp)', calories: 80 },
  { name: 'Rasam (1 bowl)', calories: 60 },
  { name: 'Vada (2 pieces)', calories: 220 },
  { name: 'Medu Vada (2 pieces)', calories: 240 },
  { name: 'Pongal (1 bowl)', calories: 280 },
  { name: 'Curd Rice (1 bowl)', calories: 250 },
  { name: 'Lemon Rice (1 bowl)', calories: 270 },
  { name: 'Tamarind Rice (1 bowl)', calories: 290 },
  { name: 'Appam (2 pieces)', calories: 180 },
  { name: 'Puttu (1 serving)', calories: 200 },
  { name: 'Kerala Fish Curry (1 serving)', calories: 280 },
  { name: 'Avial (1 serving)', calories: 160 },
  { name: 'Payasam (1 bowl)', calories: 300 },
  // ── Indian — Street Food ──────────────────────────────
  { name: 'Pani Puri (6 pieces)', calories: 200 },
  { name: 'Bhel Puri (1 plate)', calories: 180 },
  { name: 'Sev Puri (1 plate)', calories: 220 },
  { name: 'Dahi Puri (6 pieces)', calories: 240 },
  { name: 'Vada Pav (1 piece)', calories: 290 },
  { name: 'Misal Pav (1 plate)', calories: 380 },
  { name: 'Dabeli (1 piece)', calories: 220 },
  { name: 'Kathi Roll — Chicken (1 piece)', calories: 350 },
  { name: 'Kathi Roll — Paneer (1 piece)', calories: 320 },
  { name: 'Chaat (1 plate)', calories: 200 },
  { name: 'Aloo Tikki (2 pieces)', calories: 220 },
  { name: 'Corn Chaat (1 cup)', calories: 160 },
  { name: 'Roasted Chana (1 cup)', calories: 180 },
  { name: 'Sprouts Chaat (1 bowl)', calories: 150 },
  // ── Chinese ───────────────────────────────────────────
  { name: 'Fried Rice (1 bowl)', calories: 340 },
  { name: 'Egg Fried Rice (1 bowl)', calories: 380 },
  { name: 'Chicken Fried Rice (1 bowl)', calories: 420 },
  { name: 'Noodles — Hakka (1 plate)', calories: 380 },
  { name: 'Chow Mein (1 plate)', calories: 400 },
  { name: 'Dim Sum / Momos (6 pieces)', calories: 240 },
  { name: 'Spring Roll (2 pieces)', calories: 200 },
  { name: 'Manchurian — Chicken (1 serving)', calories: 320 },
  { name: 'Manchurian — Veg (1 serving)', calories: 260 },
  { name: 'Sweet and Sour Chicken (1 serving)', calories: 380 },
  { name: 'Kung Pao Chicken (1 serving)', calories: 360 },
  { name: 'Mapo Tofu (1 serving)', calories: 280 },
  { name: 'Hot and Sour Soup (1 bowl)', calories: 100 },
  { name: 'Wonton Soup (1 bowl)', calories: 180 },
  { name: 'Peking Duck (1 serving)', calories: 480 },
  { name: 'Char Siu Pork (1 serving)', calories: 350 },
  { name: 'Congee / Rice Porridge (1 bowl)', calories: 180 },
  { name: 'Steamed Bun (Baozi) (1 piece)', calories: 160 },
  { name: 'Scallion Pancake (1 piece)', calories: 200 },
  // ── Japanese ──────────────────────────────────────────
  { name: 'Sushi — Nigiri (2 pieces)', calories: 130 },
  { name: 'Sushi Roll — California (6 pieces)', calories: 250 },
  { name: 'Sashimi (6 pieces)', calories: 150 },
  { name: 'Ramen (1 bowl)', calories: 500 },
  { name: 'Udon Noodles (1 bowl)', calories: 400 },
  { name: 'Soba Noodles (1 bowl)', calories: 350 },
  { name: 'Tempura (6 pieces)', calories: 300 },
  { name: 'Tonkatsu (1 serving)', calories: 480 },
  { name: 'Teriyaki Chicken (1 serving)', calories: 380 },
  { name: 'Miso Soup (1 bowl)', calories: 50 },
  { name: 'Edamame (1 cup)', calories: 120 },
  { name: 'Gyoza (6 pieces)', calories: 240 },
  { name: 'Onigiri (1 piece)', calories: 180 },
  { name: 'Takoyaki (6 pieces)', calories: 280 },
  { name: 'Okonomiyaki (1 piece)', calories: 350 },
  { name: 'Katsu Curry (1 plate)', calories: 620 },
  { name: 'Yakitori (4 skewers)', calories: 200 },
  { name: 'Matcha Latte (1 cup)', calories: 120 },
  // ── Korean ────────────────────────────────────────────
  { name: 'Bibimbap (1 bowl)', calories: 490 },
  { name: 'Kimchi Fried Rice (1 bowl)', calories: 420 },
  { name: 'Bulgogi (1 serving)', calories: 350 },
  { name: 'Japchae (1 serving)', calories: 320 },
  { name: 'Tteokbokki (1 serving)', calories: 380 },
  { name: 'Sundubu Jjigae (1 bowl)', calories: 280 },
  { name: 'Doenjang Jjigae (1 bowl)', calories: 200 },
  { name: 'Korean Fried Chicken (6 pieces)', calories: 480 },
  { name: 'Samgyeopsal — Pork Belly (1 serving)', calories: 520 },
  { name: 'Kimchi (1 cup)', calories: 40 },
  { name: 'Kimbap (1 roll)', calories: 300 },
  { name: 'Pajeon — Scallion Pancake (1 piece)', calories: 250 },
  // ── Thai ──────────────────────────────────────────────
  { name: 'Pad Thai (1 plate)', calories: 480 },
  { name: 'Green Curry (1 serving)', calories: 380 },
  { name: 'Red Curry (1 serving)', calories: 360 },
  { name: 'Tom Yum Soup (1 bowl)', calories: 150 },
  { name: 'Tom Kha Gai (1 bowl)', calories: 220 },
  { name: 'Mango Sticky Rice (1 serving)', calories: 380 },
  { name: 'Som Tum — Papaya Salad (1 serving)', calories: 120 },
  { name: 'Massaman Curry (1 serving)', calories: 420 },
  { name: 'Pad See Ew (1 plate)', calories: 450 },
  { name: 'Thai Basil Chicken (1 serving)', calories: 340 },
  { name: 'Satay — Chicken (4 skewers)', calories: 220 },
  // ── Vietnamese ────────────────────────────────────────
  { name: 'Pho — Beef (1 bowl)', calories: 400 },
  { name: 'Pho — Chicken (1 bowl)', calories: 350 },
  { name: 'Banh Mi (1 sandwich)', calories: 440 },
  { name: 'Goi Cuon — Fresh Spring Roll (2 pieces)', calories: 140 },
  { name: 'Bun Bo Hue (1 bowl)', calories: 450 },
  { name: 'Com Tam — Broken Rice (1 plate)', calories: 520 },
  { name: 'Bun Cha (1 serving)', calories: 380 },
  { name: 'Banh Xeo — Sizzling Crepe (1 piece)', calories: 300 },
  // ── Italian ───────────────────────────────────────────
  { name: 'Pasta — Spaghetti Bolognese (1 plate)', calories: 580 },
  { name: 'Pasta — Carbonara (1 plate)', calories: 620 },
  { name: 'Pasta — Aglio e Olio (1 plate)', calories: 480 },
  { name: 'Pasta — Pesto (1 plate)', calories: 520 },
  { name: 'Pasta — Arrabiata (1 plate)', calories: 440 },
  { name: 'Pizza — Margherita (2 slices)', calories: 480 },
  { name: 'Pizza — Pepperoni (2 slices)', calories: 560 },
  { name: 'Pizza — Veggie (2 slices)', calories: 420 },
  { name: 'Risotto — Mushroom (1 plate)', calories: 480 },
  { name: 'Risotto — Seafood (1 plate)', calories: 520 },
  { name: 'Lasagna (1 serving)', calories: 580 },
  { name: 'Gnocchi (1 plate)', calories: 400 },
  { name: 'Bruschetta (2 pieces)', calories: 160 },
  { name: 'Minestrone Soup (1 bowl)', calories: 140 },
  { name: 'Tiramisu (1 slice)', calories: 380 },
  { name: 'Gelato (1 scoop)', calories: 130 },
  { name: 'Focaccia (1 slice)', calories: 200 },
  { name: 'Calzone (1 piece)', calories: 580 },
  // ── Mexican ───────────────────────────────────────────
  { name: 'Tacos — Chicken (2 pieces)', calories: 320 },
  { name: 'Tacos — Beef (2 pieces)', calories: 360 },
  { name: 'Tacos — Fish (2 pieces)', calories: 280 },
  { name: 'Burrito — Chicken (1 piece)', calories: 580 },
  { name: 'Burrito — Bean and Cheese (1 piece)', calories: 520 },
  { name: 'Quesadilla — Cheese (1 piece)', calories: 400 },
  { name: 'Quesadilla — Chicken (1 piece)', calories: 460 },
  { name: 'Enchiladas (2 pieces)', calories: 480 },
  { name: 'Nachos with Cheese (1 plate)', calories: 560 },
  { name: 'Guacamole (3 tbsp)', calories: 120 },
  { name: 'Salsa (3 tbsp)', calories: 20 },
  { name: 'Fajitas — Chicken (1 serving)', calories: 420 },
  { name: 'Tamales (2 pieces)', calories: 360 },
  { name: 'Churros (3 pieces)', calories: 280 },
  { name: 'Horchata (1 glass)', calories: 180 },
  // ── American ──────────────────────────────────────────
  { name: 'Burger — Beef (1 piece)', calories: 540 },
  { name: 'Burger — Chicken (1 piece)', calories: 480 },
  { name: 'Burger — Veggie (1 piece)', calories: 400 },
  { name: 'Hot Dog (1 piece)', calories: 290 },
  { name: 'French Fries (medium)', calories: 380 },
  { name: 'Onion Rings (1 serving)', calories: 320 },
  { name: 'Mac and Cheese (1 bowl)', calories: 480 },
  { name: 'BBQ Ribs (1 serving)', calories: 580 },
  { name: 'Grilled Cheese Sandwich (1 piece)', calories: 380 },
  { name: 'Club Sandwich (1 piece)', calories: 520 },
  { name: 'Caesar Salad (1 bowl)', calories: 280 },
  { name: 'Coleslaw (1 cup)', calories: 150 },
  { name: 'Pancakes (3 pieces)', calories: 420 },
  { name: 'Waffles (2 pieces)', calories: 380 },
  { name: 'Bagel with Cream Cheese (1 piece)', calories: 380 },
  { name: 'Cheesecake (1 slice)', calories: 420 },
  { name: 'Brownie (1 piece)', calories: 280 },
  { name: 'Chocolate Chip Cookie (2 pieces)', calories: 200 },
  { name: 'Apple Pie (1 slice)', calories: 320 },
  { name: 'Clam Chowder (1 bowl)', calories: 280 },
  { name: 'Buffalo Wings (6 pieces)', calories: 480 },
  { name: 'Corn Dog (1 piece)', calories: 260 },
  // ── Middle Eastern ────────────────────────────────────
  { name: 'Hummus (3 tbsp)', calories: 100 },
  { name: 'Falafel (4 pieces)', calories: 280 },
  { name: 'Shawarma — Chicken (1 wrap)', calories: 480 },
  { name: 'Shawarma — Lamb (1 wrap)', calories: 520 },
  { name: 'Kebab — Shish (1 serving)', calories: 320 },
  { name: 'Kebab — Doner (1 serving)', calories: 480 },
  { name: 'Pita Bread (1 piece)', calories: 160 },
  { name: 'Tabbouleh (1 cup)', calories: 120 },
  { name: 'Fattoush Salad (1 bowl)', calories: 140 },
  { name: 'Baba Ganoush (3 tbsp)', calories: 90 },
  { name: 'Mansaf — Lamb with Rice (1 plate)', calories: 680 },
  { name: 'Koshari (1 plate)', calories: 420 },
  { name: 'Shakshuka (1 serving)', calories: 280 },
  { name: 'Baklava (2 pieces)', calories: 300 },
  { name: 'Kunafa (1 serving)', calories: 380 },
  { name: 'Lentil Soup (1 bowl)', calories: 180 },
  // ── Mediterranean ─────────────────────────────────────
  { name: 'Greek Salad (1 bowl)', calories: 180 },
  { name: 'Moussaka (1 serving)', calories: 480 },
  { name: 'Spanakopita (1 piece)', calories: 260 },
  { name: 'Souvlaki (1 skewer)', calories: 200 },
  { name: 'Gyros (1 wrap)', calories: 480 },
  { name: 'Tzatziki (3 tbsp)', calories: 60 },
  { name: 'Dolmades — Stuffed Vine Leaves (4 pieces)', calories: 200 },
  { name: 'Paella — Seafood (1 plate)', calories: 520 },
  { name: 'Paella — Chicken (1 plate)', calories: 540 },
  { name: 'Gazpacho (1 bowl)', calories: 80 },
  // ── French ────────────────────────────────────────────
  { name: 'Croissant (1 piece)', calories: 280 },
  { name: 'Baguette (1 slice)', calories: 130 },
  { name: 'Quiche Lorraine (1 slice)', calories: 380 },
  { name: 'French Onion Soup (1 bowl)', calories: 220 },
  { name: 'Ratatouille (1 serving)', calories: 160 },
  { name: 'Coq au Vin (1 serving)', calories: 480 },
  { name: 'Beef Bourguignon (1 serving)', calories: 520 },
  { name: 'Crepe — Sweet (1 piece)', calories: 180 },
  { name: 'Crepe — Savoury (1 piece)', calories: 200 },
  { name: 'Eclair (1 piece)', calories: 260 },
  { name: 'Macaron (2 pieces)', calories: 160 },
  { name: 'Crème Brûlée (1 serving)', calories: 320 },
  // ── British ───────────────────────────────────────────
  { name: 'Fish and Chips (1 serving)', calories: 620 },
  { name: 'Full English Breakfast (1 plate)', calories: 780 },
  { name: 'Shepherd\'s Pie (1 serving)', calories: 480 },
  { name: 'Bangers and Mash (1 serving)', calories: 520 },
  { name: 'Beef Stew (1 bowl)', calories: 380 },
  { name: 'Scone (1 piece)', calories: 220 },
  { name: 'Victoria Sponge Cake (1 slice)', calories: 360 },
  { name: 'Beans on Toast (1 serving)', calories: 280 },
  { name: 'Cornish Pasty (1 piece)', calories: 480 },
  // ── Spanish ───────────────────────────────────────────
  { name: 'Tortilla Española (1 slice)', calories: 220 },
  { name: 'Patatas Bravas (1 serving)', calories: 280 },
  { name: 'Croquetas (4 pieces)', calories: 280 },
  { name: 'Churros with Chocolate (1 serving)', calories: 380 },
  { name: 'Gambas al Ajillo (1 serving)', calories: 240 },
  // ── Eggs & Dairy ──────────────────────────────────────
  { name: 'Boiled Egg (1 piece)', calories: 78 },
  { name: 'Fried Egg (1 piece)', calories: 90 },
  { name: 'Scrambled Eggs (2 eggs)', calories: 180 },
  { name: 'Omelette — Plain (2 eggs)', calories: 160 },
  { name: 'Omelette — Cheese (2 eggs)', calories: 240 },
  { name: 'Egg Bhurji (1 serving)', calories: 200 },
  { name: 'Milk — Full Fat (1 glass 250ml)', calories: 150 },
  { name: 'Milk — Skimmed (1 glass 250ml)', calories: 90 },
  { name: 'Curd / Yogurt (1 cup)', calories: 120 },
  { name: 'Greek Yogurt (1 cup)', calories: 130 },
  { name: 'Paneer (100g)', calories: 265 },
  { name: 'Cheese — Cheddar (30g)', calories: 120 },
  { name: 'Cheese — Mozzarella (30g)', calories: 90 },
  { name: 'Butter (1 tbsp)', calories: 100 },
  { name: 'Ghee (1 tbsp)', calories: 120 },
  { name: 'Cream (2 tbsp)', calories: 100 },
  // ── Grains & Bread ────────────────────────────────────
  { name: 'White Rice (1 cup cooked)', calories: 200 },
  { name: 'Brown Rice (1 cup cooked)', calories: 215 },
  { name: 'Basmati Rice (1 cup cooked)', calories: 210 },
  { name: 'Oats — Cooked (1 bowl)', calories: 150 },
  { name: 'Muesli (1 bowl with milk)', calories: 320 },
  { name: 'Cornflakes (1 bowl with milk)', calories: 280 },
  { name: 'White Bread (2 slices)', calories: 160 },
  { name: 'Whole Wheat Bread (2 slices)', calories: 140 },
  { name: 'Multigrain Bread (2 slices)', calories: 150 },
  { name: 'Quinoa (1 cup cooked)', calories: 220 },
  { name: 'Couscous (1 cup cooked)', calories: 175 },
  { name: 'Popcorn — Plain (2 cups)', calories: 60 },
  { name: 'Popcorn — Buttered (2 cups)', calories: 140 },
  // ── Proteins ──────────────────────────────────────────
  { name: 'Chicken Breast — Grilled (100g)', calories: 165 },
  { name: 'Chicken Thigh — Grilled (100g)', calories: 210 },
  { name: 'Salmon — Grilled (100g)', calories: 208 },
  { name: 'Tuna — Canned in Water (100g)', calories: 116 },
  { name: 'Prawns — Cooked (100g)', calories: 99 },
  { name: 'Mutton — Cooked (100g)', calories: 258 },
  { name: 'Pork — Grilled (100g)', calories: 242 },
  { name: 'Tofu — Firm (100g)', calories: 76 },
  { name: 'Tempeh (100g)', calories: 193 },
  { name: 'Lentils — Cooked (1 cup)', calories: 230 },
  { name: 'Chickpeas — Cooked (1 cup)', calories: 270 },
  { name: 'Black Beans (1 cup cooked)', calories: 227 },
  { name: 'Kidney Beans (1 cup cooked)', calories: 225 },
  // ── Vegetables ────────────────────────────────────────
  { name: 'Broccoli (1 cup)', calories: 55 },
  { name: 'Spinach (1 cup)', calories: 20 },
  { name: 'Carrot (1 medium)', calories: 25 },
  { name: 'Tomato (1 medium)', calories: 22 },
  { name: 'Cucumber (1 cup sliced)', calories: 16 },
  { name: 'Capsicum / Bell Pepper (1 medium)', calories: 30 },
  { name: 'Onion (1 medium)', calories: 44 },
  { name: 'Potato — Boiled (1 medium)', calories: 130 },
  { name: 'Sweet Potato — Boiled (1 medium)', calories: 103 },
  { name: 'Corn — Boiled (1 ear)', calories: 90 },
  { name: 'Mushrooms (1 cup)', calories: 20 },
  { name: 'Cauliflower (1 cup)', calories: 25 },
  { name: 'Peas (1 cup)', calories: 118 },
  { name: 'Beetroot (1 medium)', calories: 44 },
  { name: 'Cabbage (1 cup)', calories: 22 },
  { name: 'Zucchini (1 cup)', calories: 20 },
  { name: 'Eggplant / Brinjal (1 cup)', calories: 35 },
  { name: 'Lettuce (1 cup)', calories: 5 },
  { name: 'Kale (1 cup)', calories: 33 },
  // ── Fruits ────────────────────────────────────────────
  { name: 'Apple (1 medium)', calories: 95 },
  { name: 'Banana (1 medium)', calories: 105 },
  { name: 'Orange (1 medium)', calories: 62 },
  { name: 'Mango (1 cup)', calories: 100 },
  { name: 'Grapes (1 cup)', calories: 104 },
  { name: 'Watermelon (1 cup)', calories: 46 },
  { name: 'Pineapple (1 cup)', calories: 82 },
  { name: 'Strawberries (1 cup)', calories: 49 },
  { name: 'Blueberries (1 cup)', calories: 84 },
  { name: 'Papaya (1 cup)', calories: 55 },
  { name: 'Guava (1 medium)', calories: 68 },
  { name: 'Pomegranate (1 cup seeds)', calories: 144 },
  { name: 'Kiwi (1 medium)', calories: 42 },
  { name: 'Pear (1 medium)', calories: 101 },
  { name: 'Peach (1 medium)', calories: 58 },
  { name: 'Avocado (half)', calories: 160 },
  { name: 'Coconut Water (1 glass)', calories: 46 },
  // ── Nuts & Seeds ──────────────────────────────────────
  { name: 'Almonds (1 handful / 28g)', calories: 164 },
  { name: 'Cashews (1 handful / 28g)', calories: 157 },
  { name: 'Walnuts (1 handful / 28g)', calories: 185 },
  { name: 'Peanuts (1 handful / 28g)', calories: 161 },
  { name: 'Pistachios (1 handful / 28g)', calories: 159 },
  { name: 'Mixed Nuts (1 handful / 28g)', calories: 170 },
  { name: 'Peanut Butter (2 tbsp)', calories: 190 },
  { name: 'Almond Butter (2 tbsp)', calories: 196 },
  { name: 'Chia Seeds (2 tbsp)', calories: 138 },
  { name: 'Flaxseeds (2 tbsp)', calories: 110 },
  { name: 'Sunflower Seeds (2 tbsp)', calories: 93 },
  // ── Snacks ────────────────────────────────────────────
  { name: 'Potato Chips (1 small bag 28g)', calories: 150 },
  { name: 'Biscuits / Crackers (4 pieces)', calories: 140 },
  { name: 'Granola Bar (1 piece)', calories: 190 },
  { name: 'Protein Bar (1 piece)', calories: 220 },
  { name: 'Dark Chocolate (30g)', calories: 170 },
  { name: 'Milk Chocolate (30g)', calories: 160 },
  { name: 'Ice Cream (1 scoop)', calories: 140 },
  { name: 'Doughnut (1 piece)', calories: 300 },
  { name: 'Muffin (1 piece)', calories: 340 },
  { name: 'Cupcake (1 piece)', calories: 300 },
  { name: 'Energy Bar (1 piece)', calories: 200 },
  // ── Beverages ─────────────────────────────────────────
  { name: 'Water (1 glass)', calories: 0 },
  { name: 'Black Coffee (1 cup)', calories: 5 },
  { name: 'Coffee with Milk (1 cup)', calories: 60 },
  { name: 'Cappuccino (1 cup)', calories: 120 },
  { name: 'Latte (1 cup)', calories: 150 },
  { name: 'Black Tea (1 cup)', calories: 2 },
  { name: 'Chai — Masala Tea (1 cup)', calories: 80 },
  { name: 'Green Tea (1 cup)', calories: 2 },
  { name: 'Orange Juice (1 glass)', calories: 110 },
  { name: 'Apple Juice (1 glass)', calories: 120 },
  { name: 'Mango Juice (1 glass)', calories: 130 },
  { name: 'Smoothie — Fruit (1 glass)', calories: 200 },
  { name: 'Protein Shake (1 scoop in water)', calories: 120 },
  { name: 'Soft Drink / Cola (1 can 330ml)', calories: 140 },
  { name: 'Energy Drink (1 can 250ml)', calories: 110 },
  { name: 'Beer (1 can 330ml)', calories: 150 },
  { name: 'Wine — Red (1 glass 150ml)', calories: 125 },
  { name: 'Wine — White (1 glass 150ml)', calories: 120 },
];

/**
 * Search food database by name (case-insensitive, fuzzy word match).
 * Returns top 8 matches sorted by relevance.
 * @param {string} query
 * @returns {{ name: string, calories: number }[]}
 */
function searchFood(query) {
  if (!query || !query.trim()) return [];
  const terms = query.toLowerCase().trim().split(/\s+/);
  const scored = FOODS.map(food => {
    const lower = food.name.toLowerCase();
    let score = 0;
    terms.forEach(term => {
      if (lower.includes(term)) score += term.length; // longer match = higher score
    });
    return { food, score };
  }).filter(r => r.score > 0);
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, 8).map(r => r.food);
}
